# Generated by Django 2.1 on 2019-01-21 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FieldOfStudy',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Occupation',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('website', models.CharField(blank=True, max_length=255, null=True)),
                ('logo_url', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('admissions_contact_no', models.CharField(max_length=255)),
                ('postal_address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.IntegerField(help_text='Key of qualification', primary_key=True, serialize=False, unique=True)),
                ('qualification_id', models.IntegerField()),
                ('saqa_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('short_description', models.CharField(max_length=255)),
                ('long_description', models.CharField(max_length=255)),
                ('nqf_level', models.IntegerField()),
                ('duration_in_months', models.IntegerField()),
                ('full_time', models.BooleanField()),
                ('part_time', models.BooleanField()),
                ('credits_after_completion', models.IntegerField()),
                ('distance_learning', models.BooleanField()),
                ('estimated_annual_fee', models.IntegerField()),
                ('campus_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ford3.Campus')),
                ('modules', models.ManyToManyField(to='ford3.Module')),
                ('occupation_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ford3.Occupation')),
            ],
        ),
        migrations.CreateModel(
            name='QualificationEntranceRequirementSubject',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('minimum_score', models.IntegerField()),
                ('required', models.BooleanField()),
                ('qualification_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ford3.Qualification')),
            ],
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('assessment', models.BooleanField()),
                ('interview', models.BooleanField()),
                ('admission_point_score', models.IntegerField()),
                ('min_qualification', models.IntegerField()),
                ('qualification_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ford3.Qualification')),
            ],
        ),
        migrations.CreateModel(
            name='SecondaryInstitutionType',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SubFieldOfStudy',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('field_of_study_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ford3.FieldOfStudy')),
                ('occupation_id', models.ManyToManyField(to='ford3.Occupation')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('secondary_institution_types', models.ManyToManyField(to='ford3.SecondaryInstitutionType')),
            ],
        ),
        migrations.AddField(
            model_name='qualificationentrancerequirementsubject',
            name='subject_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ford3.Subject'),
        ),
        migrations.AddField(
            model_name='qualification',
            name='sub_field_of_study_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ford3.SubFieldOfStudy'),
        ),
        migrations.AddField(
            model_name='qualification',
            name='subjects',
            field=models.ManyToManyField(through='ford3.QualificationEntranceRequirementSubject', to='ford3.Subject'),
        ),
        migrations.AddField(
            model_name='campus',
            name='provider_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ford3.Provider'),
        ),
    ]
