# Generated by Django 2.1.5 on 2019-03-07 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ford3', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampusEvent',
            fields=[
                ('id', models.IntegerField(help_text='Key of campus event', primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('http_link', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='QualificationEvent',
            fields=[
                ('id', models.IntegerField(help_text='Key of qualification event', primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('http_link', models.CharField(max_length=255)),
                ('qualification_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ford3.Qualification')),
            ],
        ),
        migrations.AlterField(
            model_name='campus',
            name='telephone',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='provider',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='provider',
            name='provider_type',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='provider',
            name='telephone',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='campusevent',
            name='campus_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ford3.Campus'),
        ),
    ]
