# Generated by Django 2.1.5 on 2019-03-06 13:01

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ford3', '0002_auto_20190306_1253'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='qualification',
            old_name='estimated_annual_fee',
            new_name='total_cost',
        ),
        migrations.RemoveField(
            model_name='qualification',
            name='modules',
        ),
        migrations.AddField(
            model_name='campus',
            name='email',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='campus',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, help_text='The spatial point position of the campus', null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='campus',
            name='max_students_per_year',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='campus',
            name='photo_url',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='campus',
            name='physical_address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='campus',
            name='postal_address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='campus',
            name='telephone',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='physical_address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='provider_type',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='telephone',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='qualification',
            name='completion_rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='qualification',
            name='critical_skill',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='qualification',
            name='green_occupation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='qualification',
            name='high_demand_occupation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='qualification',
            name='total_cost_comment',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='requirement',
            name='aps_calculator_link',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='requirement',
            name='portfolio',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='requirement',
            name='portfolio_comment',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='provider',
            name='postal_address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Module',
        ),
        migrations.AddField(
            model_name='qualification',
            name='interests',
            field=models.ManyToManyField(to='ford3.Interest'),
        ),
    ]
