# Generated by Django 2.1.7 on 2019-05-29 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ford3', '0002_provider_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='name',
            field=models.CharField(default='', help_text="The provider's name", max_length=255),
        ),
    ]
