# Generated by Django 2.1.7 on 2019-05-31 04:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ford3', '0002_auto_20190530_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='admissions_contact_no',
            field=models.CharField(help_text='A contact number students interested in applying can use', max_length=16, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be at least 10 digits and at max 15 digits. It can starts with +(country code)', regex='^\\+?1?\\d{10,15}$')]),
        ),
        migrations.AlterField(
            model_name='provider',
            name='telephone',
            field=models.CharField(help_text="The provider's telephone number", max_length=16, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be at least 10 digits and at max 15 digits. It can starts with +(country code)', regex='^\\+?1?\\d{10,15}$')]),
        ),
    ]
