# Generated by Django 2.1.7 on 2019-03-19 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ford3', '0002_auto_20190307_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualification',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
