# Generated by Django 2.1.5 on 2019-03-18 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ford3', '0002_auto_20190307_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campus',
            name='photo_url',
        ),
        migrations.AddField(
            model_name='campus',
            name='photo',
            field=models.FileField(help_text='Representative photo of campus', null=True, upload_to='campus/photo'),
        ),
    ]
