# Generated by Django 2.1.7 on 2019-05-30 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ford3', '0002_auto_20190530_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campusevent',
            name='campus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campus_events', to='ford3.Campus'),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='campus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campus_qualifications', to='ford3.Campus'),
        ),
        migrations.AlterField(
            model_name='qualificationevent',
            name='qualification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualification_events', to='ford3.Qualification'),
        ),
    ]
