# Generated by Django 2.1.7 on 2019-05-28 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ford3', '0003_province'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='provinces',
            field=models.ManyToManyField(blank=True, to='ford3.Province'),
        ),
    ]
