# Generated by Django 2.1.7 on 2019-03-19 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ford3', '0003_auto_20190319_0744'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requirement',
            old_name='min_qualification',
            new_name='min_nqf_level',
        ),
    ]
