# Generated by Django 2.1.5 on 2019-03-07 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ford3', '0003_qualificationevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='telephone',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
