# Generated by Django 2.1.7 on 2019-05-31 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ford3', '0003_auto_20190531_0613'),
        ('ford3', '0003_auto_20190530_1952'),
    ]

    operations = [
    ]
