# Generated by Django 2.1.5 on 2019-03-21 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ford3', '0003_auto_20190319_2000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='provider',
            old_name='physical_address',
            new_name='physical_address_line_1',
        ),
        migrations.AddField(
            model_name='provider',
            name='physical_address_city',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='physical_address_line_2',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='campus',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='telephone',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
