# Generated by Django 2.1.7 on 2019-05-31 12:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ford3', '0004_merge_20190531_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campus',
            name='telephone',
            field=models.CharField(help_text="The campus' telephone number", max_length=16, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be at least 10 digits and at max 15 digits.It can start with +(country code)', regex='^\\+?1?\\d{10,15}$')]),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='telephone',
            field=models.CharField(blank=True, help_text='Prospect telephone number', max_length=16, validators=[django.core.validators.RegexValidator(message='Phone number must be at least 10 digits and at max 15 digits.It can start with +(country code)', regex='^\\+?1?\\d{10,15}$')]),
        ),
        migrations.AlterField(
            model_name='provider',
            name='admissions_contact_no',
            field=models.CharField(help_text='A contact number students interested in applying can use', max_length=16, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be at least 10 digits and at max 15 digits.It can start with +(country code)', regex='^\\+?1?\\d{10,15}$')]),
        ),
        migrations.AlterField(
            model_name='provider',
            name='telephone',
            field=models.CharField(help_text="The provider's telephone number", max_length=16, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be at least 10 digits and at max 15 digits.It can start with +(country code)', regex='^\\+?1?\\d{10,15}$')]),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='campus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualification_set', to='ford3.Campus'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='qualification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirement_set', to='ford3.Qualification'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
