# Generated by Django 2.1.7 on 2019-05-28 12:06

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ford3', '0006_provider_province'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampusUser',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('ford3.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ProviderUser',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('ford3.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
