# Generated by Django 2.1.7 on 2019-03-20 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ford3', '0006_auto_20190320_0407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualification',
            name='interests',
            field=models.ManyToManyField(blank=True, null=True, to='ford3.Interest'),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='occupation_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ford3.Occupation'),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='sub_field_of_study_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ford3.SubFieldOfStudy'),
        ),
    ]
