# Generated by Django 2.1.5 on 2019-03-07 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ford3', '0006_auto_20190307_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='telephone',
            field=models.IntegerField(default=0),
        ),
    ]
