# Generated by Django 2.1.7 on 2019-06-07 06:59

import django.core.validators
from django.db import migrations, models
import ford3.managers.user_manager


class Migration(migrations.Migration):

    dependencies = [
        ('ford3', '0006_auto_20190603_1623'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', ford3.managers.user_manager.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='qualification',
            name='duration_time_repr',
            field=models.CharField(blank=True, help_text='Represent the duration of the qualification in month or year', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='campus',
            name='telephone',
            field=models.CharField(help_text="The campus' telephone number", max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='provider',
            name='admissions_contact_no',
            field=models.CharField(help_text='A contact number students interested in applying can use', max_length=16, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be at least 10 digits and at max 15 digits. It can start with +(country code).', regex='^\\+?1?\\d{10,15}$')]),
        ),
        migrations.AlterField(
            model_name='provider',
            name='telephone',
            field=models.CharField(help_text="The provider's telephone number", max_length=16, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be at least 10 digits and at max 15 digits. It can start with +(country code).', regex='^\\+?1?\\d{10,15}$')]),
        ),
    ]
