# Generated by Django 2.1.5 on 2019-03-07 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ford3', '0007_auto_20190307_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='telephone',
            field=models.BigIntegerField(default=0),
        ),
    ]
