# Generated by Django 2.1.7 on 2019-03-20 04:51

from django.db import migrations, models
import ford3.enums.saqa_qualification_level


class Migration(migrations.Migration):

    dependencies = [
        ('ford3', '0007_auto_20190320_0408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='admission_point_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='aps_calculator_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='assessment',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='interview',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='min_nqf_level',
            field=models.CharField(blank=True, choices=[(ford3.enums.saqa_qualification_level.SaqaQualificationLevel('Grade 9'), 'Grade 9'), (ford3.enums.saqa_qualification_level.SaqaQualificationLevel('Grade 10 and National (vocational) Certificates level 2'), 'Grade 10 and National (vocational) Certificates level 2'), (ford3.enums.saqa_qualification_level.SaqaQualificationLevel('Grade 11 and National (vocational) Certificates level 3'), 'Grade 11 and National (vocational) Certificates level 3'), (ford3.enums.saqa_qualification_level.SaqaQualificationLevel('Grade 12 (National Senior Certificate) and National (vocational) Cert.'), 'Grade 12 (National Senior Certificate) and National (vocational) Cert.'), (ford3.enums.saqa_qualification_level.SaqaQualificationLevel('Higher Certificates and Advanced National (vocational) Cert.'), 'Higher Certificates and Advanced National (vocational) Cert.'), (ford3.enums.saqa_qualification_level.SaqaQualificationLevel('National Diploma and Advanced certificates'), 'National Diploma and Advanced certificates'), (ford3.enums.saqa_qualification_level.SaqaQualificationLevel("Bachelor's degree, Advanced Diplomas, Post Graduate Certificate and B-tech"), "Bachelor's degree, Advanced Diplomas, Post Graduate Certificate and B-tech"), (ford3.enums.saqa_qualification_level.SaqaQualificationLevel('Honours degree, Post Graduate diploma and Professional Qualifications'), 'Honours degree, Post Graduate diploma and Professional Qualifications'), (ford3.enums.saqa_qualification_level.SaqaQualificationLevel("Master's degree"), "Master's degree"), (ford3.enums.saqa_qualification_level.SaqaQualificationLevel("Doctor's degree"), "Doctor's degree")], max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='portfolio',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='portfolio_comment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
