# Generated by Django 2.1.7 on 2019-06-07 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ford3', '0007_auto_20190607_0859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qualification',
            name='duration_in_months',
        ),
        migrations.AddField(
            model_name='qualification',
            name='duration',
            field=models.IntegerField(blank=True, help_text='How long the qualification takes to complete', null=True),
        ),
    ]
