# Generated by Django 2.1.7 on 2019-06-11 11:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ford3', '0008_auto_20190607_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualification',
            name='published',
            field=models.BooleanField(blank=True, default=False, help_text='Has this qualification been published?', null=True),
        ),
        migrations.AddField(
            model_name='qualification',
            name='ready_to_publish',
            field=models.BooleanField(blank=True, default=False, help_text="Has the qualification's details been completed in enough detail to allow publication.", null=True),
        ),
        migrations.AlterField(
            model_name='campus',
            name='telephone',
            field=models.CharField(help_text="The campus' switchboard", max_length=16, null=True),
        )
    ]
