# Generated by Django 2.1.7 on 2019-03-20 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ford3', '0009_auto_20190320_0658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qualification',
            name='qualification_id',
        ),
    ]
