# Generated by Django 2.1.9 on 2019-06-13 08:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ford3', '0009_auto_20190611_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='telephone',
            field=models.CharField(help_text="The provider's switchboard", max_length=16, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be at least 10 digits and at max 15 digits. It can start with +(country code).', regex='^\\+?1?\\d{10,15}$')]),
        ),
        migrations.AlterField(
            model_name='provider',
            name='website',
            field=models.URLField(blank=True, help_text="The provider's main web page", max_length=255, null=True),
        ),
    ]
