# Generated by Django 2.1.7 on 2019-06-13 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ford3', '0010_auto_20190613_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualification',
            name='short_description',
            field=models.CharField(blank=True, help_text='A short description of what the qualification entails', max_length=250, null=True),
        ),
    ]
