# Generated by Django 2.1.7 on 2019-03-20 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ford3', '0011_auto_20190320_0714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualification',
            name='saqa_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
