# Generated by Django 2.1.7 on 2019-06-14 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ford3', '0011_auto_20190614_1321'),
        ('ford3', '0011_auto_20190613_2234'),
    ]

    operations = [
    ]
