# Generated by Django 2.1.7 on 2019-06-14 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ford3', '0012_merge_20190614_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='assessment',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='assessment_requirements',
        ),
        migrations.AddField(
            model_name='requirement',
            name='assessment_comment',
            field=models.CharField(blank=True, help_text='Additional information regarding the assessment involved.', max_length=255, null=True),
        ),
    ]
