# Generated by Django 2.1.7 on 2019-03-20 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ford3', '0012_auto_20190320_0735'),
        ('ford3', '0003_auto_20190318_1240'),
    ]

    operations = [
    ]
