# Generated by Django 2.1.9 on 2019-06-17 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ford3', '0013_auto_20190614_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='account_activated',
        ),
    ]
