# Generated by Django 2.1.7 on 2019-03-21 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ford3', '0013_merge_20190320_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
