# Generated by Django 2.1.9 on 2019-06-17 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ford3', '0014_remove_user_account_activated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
