# Generated by Django 2.1.7 on 2019-03-21 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ford3', '0014_auto_20190321_0406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qualification',
            name='occupation_id',
        ),
        migrations.AddField(
            model_name='qualification',
            name='occupations',
            field=models.ManyToManyField(blank=True, null=True, to='ford3.Occupation'),
        ),
        migrations.AlterField(
            model_name='occupation',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='occupation',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
