# Generated by Django 2.1.7 on 2019-03-22 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ford3', '0005_auto_20190322_0958'),
        ('ford3', '0015_auto_20190320_1239'),
    ]

    operations = [
    ]
