# Generated by Django 2.1.7 on 2019-03-21 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ford3', '0015_auto_20190320_1239'),
        ('ford3', '0015_auto_20190321_0732'),
    ]

    operations = [
    ]
