# Generated by Django 2.1.7 on 2019-03-21 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ford3', '0016_merge_20190321_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occupation',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
