# Generated by Django 2.1.9 on 2019-06-21 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ford3', '0017_auto_20190621_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualification',
            name='critical_skill',
            field=models.BooleanField(blank=True, help_text='Would the skill obtained by completing this qualification be considered a critical skill?', null=True),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='distance_learning',
            field=models.BooleanField(blank=True, help_text='Does this qualification have a distance learning option?', null=True),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='green_occupation',
            field=models.BooleanField(blank=True, help_text='Would the occupations this qualification prepares you for be considered environmentally friendly?', null=True),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='high_demand_occupation',
            field=models.BooleanField(blank=True, help_text='Are the occupations this qualification prepares you for in high demand?', null=True),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='assessment',
            field=models.BooleanField(blank=True, help_text='Is there an assessment as part of the application process?', null=True),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='interview',
            field=models.BooleanField(blank=True, help_text='Is there an interview as part of the application process?', null=True),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='portfolio',
            field=models.BooleanField(blank=True, help_text='Does the applicant need to submit a portfolio as part of the application process?', null=True),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='require_aps_score',
            field=models.BooleanField(blank=True, help_text='Does the applicant need to acheive a certain APS score?', null=True),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='require_certain_subjects',
            field=models.BooleanField(blank=True, help_text='Are there specific subjects listed as a prerequisite for this qualification', null=True),
        ),
    ]
