# Generated by Django 2.1.7 on 2019-03-21 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ford3', '0017_auto_20190321_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualificationevent',
            name='event_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qualificationevent',
            name='date_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qualificationevent',
            name='date_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qualificationevent',
            name='http_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='qualificationevent',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='qualificationevent',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
