# Generated by Django 2.1.9 on 2019-07-19 13:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ford3', '0018_auto_20190621_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campus',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='campus_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='campus',
            name='deleted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='campus_deleted_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='campus',
            name='edited_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='campus_edited_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='campus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='qualification_set', to='ford3.Campus'),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='qualification_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='deleted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='qualification_deleted_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='edited_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='qualification_edited_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
