# Generated by Django 2.1.7 on 2019-03-21 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ford3', '0018_auto_20190321_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualificationevent',
            name='other_event',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
