# Generated by Django 2.1.7 on 2019-03-25 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ford3', '0020_auto_20190322_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='occupation',
            name='green_occupation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='occupation',
            name='scarce_skill',
            field=models.BooleanField(default=False),
        ),
    ]
