# Generated by Django 2.1.7 on 2019-03-26 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ford3', '0021_auto_20190325_1114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qualificationevent',
            old_name='qualification_id',
            new_name='qualification',
        ),
    ]
