# Generated by Django 2.1.7 on 2019-03-25 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ford3', '0021_auto_20190325_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='occupation',
            name='tasks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
