# Generated by Django 2.1.7 on 2019-03-26 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ford3', '0022_auto_20190326_0846'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requirement',
            old_name='qualification_id',
            new_name='qualification',
        ),
    ]
