# Generated by Django 2.1.7 on 2019-03-26 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ford3', '0023_auto_20190326_0848'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campusevent',
            old_name='campus_id',
            new_name='campus',
        ),
        migrations.RenameField(
            model_name='qualificationentrancerequirementsubject',
            old_name='qualification_id',
            new_name='qualification',
        ),
        migrations.RenameField(
            model_name='qualificationentrancerequirementsubject',
            old_name='subject_id',
            new_name='subject',
        ),
        migrations.RenameField(
            model_name='subfieldofstudy',
            old_name='field_of_study_id',
            new_name='field_of_study',
        ),
        migrations.AlterField(
            model_name='campusevent',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='fieldofstudy',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='subfieldofstudy',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
