# Generated by Django 2.1.7 on 2019-03-27 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ford3', '0024_auto_20190326_0850'),
        ('ford3', '0022_occupation_tasks'),
    ]

    operations = [
    ]
