# Generated by Django 2.1.7 on 2019-03-27 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ford3', '0022_occupation_tasks'),
        ('ford3', '0024_auto_20190326_0850'),
        ('ford3', '0021_auto_20190325_1450'),
        ('ford3', '0017_auto_20190322_1240'),
    ]

    operations = [
    ]
