# Generated by Django 2.1.9 on 2019-07-20 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ford3', '0021_admissionpointscore'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requirement',
            name='admission_point_score',
        ),
    ]
