# Generated by Django 2.1.7 on 2019-03-27 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ford3', '0025_merge_20190327_1336'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='SAQAQualification',
        #     fields=[
        #         ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('saqa_id', models.IntegerField()),
        #         ('nqf_level', models.IntegerField(blank=True, null=True)),
        #         ('name', models.CharField(max_length=255)),
        #     ],
        # ),
    ]
