# Generated by Django 2.1.7 on 2019-03-28 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ford3', '0025_merge_20190327_1336'),
    ]

    operations = [
        migrations.CreateModel(
            name='SAQAQualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saqa_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('nqf_level', models.IntegerField(blank=True, null=True)),
                ('sub_field_of_study', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ford3.SubFieldOfStudy')),
            ],
        ),
        migrations.RemoveField(
            model_name='qualification',
            name='nqf_level',
        ),
        migrations.RemoveField(
            model_name='qualification',
            name='saqa_id',
        ),
        migrations.RemoveField(
            model_name='qualification',
            name='sub_field_of_study',
        ),
        migrations.AlterField(
            model_name='qualification',
            name='interests',
            field=models.ManyToManyField(blank=True, to='ford3.Interest'),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='occupations',
            field=models.ManyToManyField(blank=True, to='ford3.Occupation'),
        ),
        migrations.AddField(
            model_name='qualification',
            name='saqa_qualification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ford3.SAQAQualification'),
        ),
    ]
