# Generated by Django 2.1.7 on 2019-03-27 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ford3', '0025_merge_20190326_1317'),
        ('ford3', '0021_auto_20190325_1450'),
        ('ford3', '0025_merge_20190327_0845'),
    ]

    operations = [
    ]
