# Generated by Django 2.1.9 on 2019-07-21 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ford3', '0026_auto_20190720_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='is_other',
            field=models.BooleanField(blank=True, default=False, help_text='Is the subject any other subject', null=True),
        ),
    ]
