# Generated by Django 2.1.7 on 2019-03-27 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ford3', '0025_merge_20190326_1352'),
        ('ford3', '0026_merge_20190327_1002'),
    ]

    operations = [
    ]
