# Generated by Django 2.1.7 on 2019-03-27 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ford3', '0027_merge_20190327_1251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campus',
            name='physical_address',
        ),
        migrations.RemoveField(
            model_name='campus',
            name='postal_address',
        ),
        migrations.AddField(
            model_name='campus',
            name='physical_address_city',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='campus',
            name='physical_address_postal_code',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='campus',
            name='physical_address_street_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='campus',
            name='postal_address_city',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='campus',
            name='postal_address_postal_code',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='campus',
            name='postal_address_street_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
