# Generated by Django 2.1.7 on 2019-03-27 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ford3', '0027_auto_20190327_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualification',
            name='interests',
            field=models.ManyToManyField(blank=True, to='ford3.Interest'),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='occupations',
            field=models.ManyToManyField(blank=True, to='ford3.Occupation'),
        ),
    ]
