# Generated by Django 2.1.11 on 2019-10-04 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ford3', '0027_subject_is_other'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualification',
            name='http_link',
            field=models.URLField(blank=True, help_text='A link to a web page containing additional details regarding this qualification', max_length=255, null=True),
        ),
    ]
