# Generated by Django 2.1.7 on 2019-03-27 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ford3', '0027_merge_20190327_1030'),
        ('ford3', '0028_auto_20190327_1307'),
    ]

    operations = [
    ]
