# Generated by Django 2.1.7 on 2019-03-28 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ford3', '0030_merge_20190328_1254'),
        ('ford3', '0029_merge_20190328_1247'),
    ]

    operations = [
    ]
