# Generated by Django 2.1.7 on 2019-04-15 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ford3', '0031_merge_20190328_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='campus',
            name='postal_address_differs',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
