# Generated by Django 2.1.7 on 2019-04-16 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ford3', '0032_campus_postal_address_differs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campus',
            old_name='physical_address_street_name',
            new_name='physical_address_line_1',
        ),
        migrations.RenameField(
            model_name='campus',
            old_name='postal_address_street_name',
            new_name='postal_address_line_1',
        ),
        migrations.AddField(
            model_name='campus',
            name='physical_address_line_2',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='campus',
            name='postal_address_line_2',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
