# Generated by Django 2.1.7 on 2019-04-16 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ford3', '0032_auto_20190416_2138'),
        ('ford3', '0033_auto_20190416_1305'),
    ]

    operations = [
    ]
