# Generated by Django 2.1.7 on 2019-04-26 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ford3', '0034_auto_20190418_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campus',
            name='email',
            field=models.EmailField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='campus',
            name='max_students_per_year',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='campusevent',
            name='http_link',
            field=models.URLField(max_length=255, null=True),
        ),
    ]
