# Generated by Django 2.1.7 on 2019-04-26 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ford3', '0034_auto_20190418_0941'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prospect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Prospect first and last name', max_length=150)),
                ('telephone', models.CharField(help_text='Prospect telephone number', max_length=150)),
                ('email', models.EmailField(help_text='Prospect email address', max_length=254)),
            ],
        ),
    ]
