# Generated by Django 2.1.7 on 2019-04-30 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ford3', '0035_prospect'),
        ('ford3', '0035_auto_20190426_1743'),
    ]

    operations = [
    ]
