# Generated by Django 2.1.7 on 2019-05-02 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ford3', '0034_merge_20190416_2147'),
        ('ford3', '0036_prospect'),
    ]

    operations = [
    ]
