# Generated by Django 2.1.7 on 2019-05-03 11:51

from django.db import migrations, models
import ford3.enums.saqa_qualification_level


class Migration(migrations.Migration):

    dependencies = [
        ('ford3', '0037_merge_20190502_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campus',
            name='email',
            field=models.EmailField(help_text="The campus' email", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='campus',
            name='max_students_per_year',
            field=models.PositiveIntegerField(help_text='Maximum number of students', null=True),
        ),
        migrations.AlterField(
            model_name='campus',
            name='name',
            field=models.CharField(help_text='The name of the campus', max_length=255),
        ),
        migrations.AlterField(
            model_name='campus',
            name='physical_address_city',
            field=models.CharField(help_text="The campus' physical address city", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='campus',
            name='physical_address_line_1',
            field=models.CharField(help_text="The campus' physical address details", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='campus',
            name='physical_address_line_2',
            field=models.CharField(help_text="The campus' physical address details", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='campus',
            name='physical_address_postal_code',
            field=models.CharField(help_text="The campus' physical address postal code", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='campus',
            name='postal_address_city',
            field=models.CharField(help_text="The campus' postal address city", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='campus',
            name='postal_address_differs',
            field=models.BooleanField(default=False, help_text='Is the postal address different from the physical address?', null=True),
        ),
        migrations.AlterField(
            model_name='campus',
            name='postal_address_line_1',
            field=models.CharField(help_text="The campus' postal address", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='campus',
            name='postal_address_line_2',
            field=models.CharField(help_text="The campus' postal address", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='campus',
            name='postal_address_postal_code',
            field=models.CharField(help_text="The campus' postal adress code", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='campus',
            name='telephone',
            field=models.CharField(help_text="The campus' telephone number", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='campusevent',
            name='date_end',
            field=models.DateField(help_text='The date on which the event ends'),
        ),
        migrations.AlterField(
            model_name='campusevent',
            name='date_start',
            field=models.DateField(help_text='The date on which the event starts'),
        ),
        migrations.AlterField(
            model_name='campusevent',
            name='http_link',
            field=models.URLField(help_text='A link to a web page containing additional details regarding this event', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='campusevent',
            name='name',
            field=models.CharField(help_text='The name of this event', max_length=255),
        ),
        migrations.AlterField(
            model_name='fieldofstudy',
            name='name',
            field=models.CharField(help_text="The field of study's name", max_length=255),
        ),
        migrations.AlterField(
            model_name='interest',
            name='name',
            field=models.CharField(help_text='A short identifier for the interest', max_length=255),
        ),
        migrations.AlterField(
            model_name='occupation',
            name='description',
            field=models.TextField(blank=True, help_text='A short description of the occupation', null=True),
        ),
        migrations.AlterField(
            model_name='occupation',
            name='green_occupation',
            field=models.BooleanField(default=False, help_text='Is this an occupation suited as a good first job'),
        ),
        migrations.AlterField(
            model_name='occupation',
            name='name',
            field=models.CharField(help_text="The occupation's name", max_length=255),
        ),
        migrations.AlterField(
            model_name='occupation',
            name='scarce_skill',
            field=models.BooleanField(default=False, help_text='Would this occupation be consider a scarce skill'),
        ),
        migrations.AlterField(
            model_name='occupation',
            name='tasks',
            field=models.TextField(blank=True, help_text='A short summary of tasks involved with this occupation', null=True),
        ),
        migrations.AlterField(
            model_name='provider',
            name='admissions_contact_no',
            field=models.CharField(help_text='A contact number students interested in applying can use', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='provider',
            name='email',
            field=models.CharField(help_text='The email address interested parties can reach you at', max_length=255),
        ),
        migrations.AlterField(
            model_name='provider',
            name='name',
            field=models.CharField(blank=True, default='', help_text="The provider's name", max_length=255),
        ),
        migrations.AlterField(
            model_name='provider',
            name='physical_address_city',
            field=models.CharField(help_text='The city which the provider is in', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='provider',
            name='physical_address_line_1',
            field=models.CharField(help_text="Details of the provider's physical address", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='provider',
            name='physical_address_line_2',
            field=models.CharField(help_text="Details of the provider's physical address", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='provider',
            name='physical_address_postal_code',
            field=models.CharField(help_text="The provider's 4 digit postal code", max_length=4),
        ),
        migrations.AlterField(
            model_name='provider',
            name='postal_address_city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='provider',
            name='postal_address_line_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='provider',
            name='postal_address_line_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='provider',
            name='postal_address_postal_code',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='provider',
            name='provider_logo',
            field=models.ImageField(blank=True, help_text="The provider's logo", upload_to='provider_logo'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='provider_type',
            field=models.CharField(default='', help_text='The type of the institution', max_length=255),
        ),
        migrations.AlterField(
            model_name='provider',
            name='telephone',
            field=models.CharField(help_text="The provider's telephone number", max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='provider',
            name='website',
            field=models.CharField(blank=True, help_text="The provider's main web page", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='completion_rate',
            field=models.IntegerField(blank=True, default=0, help_text='What has the completion rate for this qualifcation been?', null=True),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='credits_after_completion',
            field=models.IntegerField(blank=True, help_text='How many credits are awarded after completion?', null=True),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='critical_skill',
            field=models.BooleanField(blank=True, default=False, help_text='Would the skill obtained by completing this qualification be considered a critical skill?', null=True),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='distance_learning',
            field=models.BooleanField(blank=True, default=False, help_text='Does this qualification have a distance learning option?', null=True),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='duration_in_months',
            field=models.IntegerField(blank=True, help_text='How long the qualification takes to complete (in months)', null=True),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='full_time',
            field=models.BooleanField(blank=True, default=False, help_text='Can this qualification be completed on a full-time basis?', null=True),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='green_occupation',
            field=models.BooleanField(blank=True, default=False, help_text='Would the occupations this qualification prepares you for be considered environmentally friendly?', null=True),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='high_demand_occupation',
            field=models.BooleanField(blank=True, default=False, help_text='Are the occupations this qualification prepares you for in high demand?', null=True),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='long_description',
            field=models.CharField(blank=True, help_text='A longer description of the qualification for the student who is interested and would like to know more', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='name',
            field=models.CharField(help_text="The qualification's name", max_length=255),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='part_time',
            field=models.BooleanField(blank=True, default=False, help_text='Can this qualification be completed on a part-time basis?', null=True),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='short_description',
            field=models.CharField(blank=True, help_text='A short description of what the qualification entails', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='What is the total cost to complete this qualification?', max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='total_cost_comment',
            field=models.CharField(blank=True, help_text='Any comments regarding the cost and payment options of this qualification should be filled in here', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='qualificationentrancerequirementsubject',
            name='minimum_score',
            field=models.IntegerField(blank=True, help_text='The minimum score required for this subject', null=True),
        ),
        migrations.AlterField(
            model_name='qualificationentrancerequirementsubject',
            name='required',
            field=models.BooleanField(blank=True, default=False, help_text='Is this subject required?', null=True),
        ),
        migrations.AlterField(
            model_name='qualificationevent',
            name='date_end',
            field=models.DateField(blank=True, help_text='When does this event end?', null=True),
        ),
        migrations.AlterField(
            model_name='qualificationevent',
            name='date_start',
            field=models.DateField(blank=True, help_text='When does this event start?', null=True),
        ),
        migrations.AlterField(
            model_name='qualificationevent',
            name='http_link',
            field=models.CharField(blank=True, help_text='A link to a webpage with additional details regarding this event', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='qualificationevent',
            name='name',
            field=models.CharField(blank=True, help_text='A short identifier for the event', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='admission_point_score',
            field=models.IntegerField(blank=True, help_text='The admission point score required for the qualification', null=True),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='aps_calculator_link',
            field=models.URLField(blank=True, help_text='A link a calculator or the specifications for calculating the required APS score.', null=True),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='assessment',
            field=models.BooleanField(blank=True, default=False, help_text='Is there an assessment as part of the application process?', null=True),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='description',
            field=models.CharField(blank=True, help_text='A summary of the requirements and type of requirements required for the assocaited qualification', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='interview',
            field=models.BooleanField(blank=True, default=False, help_text='Is there an interview as part of the application process?', null=True),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='min_nqf_level',
            field=models.CharField(blank=True, choices=[(ford3.enums.saqa_qualification_level.SaqaQualificationLevel('Grade 9'), 'Grade 9'), (ford3.enums.saqa_qualification_level.SaqaQualificationLevel('Grade 10 and National (vocational) Certificates level 2'), 'Grade 10 and National (vocational) Certificates level 2'), (ford3.enums.saqa_qualification_level.SaqaQualificationLevel('Grade 11 and National (vocational) Certificates level 3'), 'Grade 11 and National (vocational) Certificates level 3'), (ford3.enums.saqa_qualification_level.SaqaQualificationLevel('Grade 12 (National Senior Certificate) and National (vocational) Cert.'), 'Grade 12 (National Senior Certificate) and National (vocational) Cert.'), (ford3.enums.saqa_qualification_level.SaqaQualificationLevel('Higher Certificates and Advanced National (vocational) Cert.'), 'Higher Certificates and Advanced National (vocational) Cert.'), (ford3.enums.saqa_qualification_level.SaqaQualificationLevel('National Diploma and Advanced certificates'), 'National Diploma and Advanced certificates'), (ford3.enums.saqa_qualification_level.SaqaQualificationLevel("Bachelor's degree, Advanced Diplomas, Post Graduate Certificate and B-tech"), "Bachelor's degree, Advanced Diplomas, Post Graduate Certificate and B-tech"), (ford3.enums.saqa_qualification_level.SaqaQualificationLevel('Honours degree, Post Graduate diploma and Professional Qualifications'), 'Honours degree, Post Graduate diploma and Professional Qualifications'), (ford3.enums.saqa_qualification_level.SaqaQualificationLevel("Master's degree"), "Master's degree"), (ford3.enums.saqa_qualification_level.SaqaQualificationLevel("Doctor's degree"), "Doctor's degree")], help_text='The minimum NQF level a person needs to have obtained to apply for this qualification', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='portfolio',
            field=models.BooleanField(blank=True, default=False, help_text='Does the applicant need to submit a portfolio as part of the application process?', null=True),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='portfolio_comment',
            field=models.CharField(blank=True, help_text='Additional information regarding the portfolio to be submitted', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='require_aps_score',
            field=models.BooleanField(blank=True, default=False, help_text='Does the applicant need to acheive a certain APS score?', null=True),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='require_certain_subjects',
            field=models.BooleanField(blank=True, default=False, help_text='Are there specific subjects listed as a prerequisite for this qualification', null=True),
        ),
        migrations.AlterField(
            model_name='saqaqualification',
            name='name',
            field=models.CharField(help_text='The name of the qualification as approved by SAQA', max_length=255),
        ),
        migrations.AlterField(
            model_name='saqaqualification',
            name='nqf_level',
            field=models.IntegerField(blank=True, help_text='The NQF level SAQA has attributed to this qualification', null=True),
        ),
        migrations.AlterField(
            model_name='saqaqualification',
            name='saqa_id',
            field=models.IntegerField(help_text='The ID of the qualification as listed in the SAQA database'),
        ),
        migrations.AlterField(
            model_name='secondaryinstitutiontype',
            name='name',
            field=models.CharField(help_text='The name of the secondary institution type', max_length=255),
        ),
        migrations.AlterField(
            model_name='subfieldofstudy',
            name='name',
            field=models.CharField(help_text='A short identifier for the sub field of study', max_length=255),
        ),
        migrations.AlterField(
            model_name='subject',
            name='description',
            field=models.CharField(blank=True, help_text='A short description of what the learner can expect to learn whilst completing this subject', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(help_text='The name of the subject', max_length=255),
        ),
    ]
