# Generated by Django 2.1.7 on 2019-05-02 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ford3', '0037_merge_20190502_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='saqaqualification',
            name='creator_provider_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ford3.Provider'),
        ),
    ]
