# Generated by Django 2.1.7 on 2019-05-02 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ford3', '0038_saqaqualification_creator_provider_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='saqaqualification',
            name='accredited',
            field=models.BooleanField(default=True),
        ),
    ]
