# Generated by Django 2.1.7 on 2019-05-02 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ford3', '0039_saqaqualification_accredited'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saqaqualification',
            old_name='creator_provider_id',
            new_name='creator_provider',
        ),
    ]
