# Generated by Django 2.1.7 on 2019-05-07 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ford3', '0040_auto_20190502_1801'),
        ('ford3', '0038_auto_20190503_1351'),
    ]

    operations = [
    ]
