# Generated by Django 2.1.7 on 2019-05-14 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ford3', '0041_merge_20190507_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When this record was created', null=True),
        ),
        migrations.AddField(
            model_name='qualification',
            name='edited_at',
            field=models.DateTimeField(auto_now=True, help_text='The last time this record was edited', null=True),
        ),
        migrations.AlterField(
            model_name='saqaqualification',
            name='name',
            field=models.CharField(help_text='The name of the qualification as approved by SAQA', max_length=255, null=True),
        ),
    ]
