# Generated by Django 2.1.7 on 2019-05-16 11:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ford3', '0042_auto_20190514_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='saqaqualification',
            name='field_of_study',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ford3.FieldOfStudy'),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2019, 5, 16, 13, 12, 13, 836796)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='qualification',
            name='edited_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2019, 5, 16, 13, 12, 24, 469313)),
            preserve_default=False,
        ),
    ]
