# Generated by Django 2.1.7 on 2019-05-16 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ford3', '0043_auto_20190516_1312'),
        ('ford3', '0042_auto_20190515_1501'),
    ]

    operations = [
    ]
