# Generated by Django 2.1.7 on 2019-05-16 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ford3', '0044_merge_20190516_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='campusevent',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
