from ford3.models.requirement import * # noqa
from ford3.models.qualification import * # noqa
from ford3.models.qualification_event import * # noqa
from ford3.models.qualification_entrance_requirement_subject import * # noqa
from ford3.models.campus import * # noqa
from ford3.models.campus_event import * # noqa
from ford3.models.provider import * # noqa
from ford3.models.occupation import * # noqa
from ford3.models.field_of_study import * # noqa
from ford3.models.sub_field_of_study import * # noqa
from ford3.models.subject import * # noqa
from ford3.models.secondary_institution_type import * # noqa
from ford3.models.qualification_event import * # noqa
from ford3.models.interest import * # noqa
from ford3.models.saqa_qualification import * # noqa
from ford3.models.prospect import * # noqa
from ford3.models.user import User # noqa
