from ford3.models.requirement import *
from ford3.models.qualification import *
from ford3.models.qualification_entrance_requirement_subject import *
from ford3.models.campus import *
from ford3.models.provider import *
from ford3.models.occupation import *
from ford3.models.field_of_study import *
from ford3.models.sub_field_of_study import *
from ford3.models.subject import *
from ford3.models.module import *
from ford3.models.secondary_institution_type import *
